---
version: '2'
services:
  newsblur:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: newsblur
    links:
      - mongo
      - postgres
      - elasticsearch
      - redis
    ports:
      - '8000:8000'

  postgres:
    image: postgres:9
    environment:
      - POSTGRES_USER=newsblur
      - POSTGRES_PASSWORD=newsblur
    ports:
      - '5432:5432'
    volumes:
      - ./docker/postgres:/docker-entrypoint-initdb.d

  redis:
    image: redis:3
    ports:
      - '6379:6379'

  elasticsearch:
    image: elasticsearch:1.7
    ports:
      - '9200:9200'

  mongo:
    image: mongo:3.2
    ports:
      - '27017:27017'
    command: mongod --smallfiles
